name: Feature Branch Workflow  
on:  
  push:  
    branches:  
      - "feature/*"  
jobs:  
  test:  
    runs-on: ubuntu-latest  
    steps:    
      - name: Run Tests  
        run: echo "Running tests on feature branches!"
