name: Deploy Pipeline

on:
  push:
    branches:
      - release/*
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          version: '18'

      - name: Install dependencies
        run: npm install

      - name: Deploy Based on Branch
        env:
          STAGING_API_KEY: ${{ secrets.STAGING_API_KEY }}
          PROD_API_KEY: ${{ secrets.PROD_API_KEY }}
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          
          if [[ "$BRANCH_NAME" == release/* ]]; then
            echo "Deploying to Staging Environment"
            # Run staging deploy script/command
            ./scripts/deploy-staging.sh
          elif [[ "$BRANCH_NAME" == "main" ]]; then
            echo "Deploying to Production Environment"
            # Run production deploy script/command
            ./scripts/deploy-prod.sh
          fi
